basePath: /api
definitions:
  auth.RegisterInput:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  gorm.DeletedAt:
    $ref: '#/definitions/sql.NullTime'
  models.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
        type: object
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  license: {}
  version: "1.0"
paths:
  /register:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User Register information
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Register an user
swagger: "2.0"
